/** Step 2 보완 패치 시험 — 쪽별 곡 연결 · 건반 · 유튜브 · 단축키 · 반응형 · 자동 맞춤 · 필기 개선 (진짜 크롬 + 시험용 서버) */
const L = require('./e2e-lib'); const { check, sleep } = L;
const S = require('./e2e-server');
const SONGS = [{ title: 'Amazing Grace', key: 'G', bpm: 120, form: 'V1-C', team: 'T' }, { title: 'Second Song', key: 'Bb', bpm: 90, form: 'Intro-V-C', team: '', link: 'https://youtu.be/dQw4w9WgXcQ' }];
const MULTI = [{ id: 'FILEID_MULTI0001', name: 'Sunday All Songs.pdf' }];
(async () => {
  const port = await S.start(0), base = 'http://127.0.0.1' + ':' + port;
  const br = await L.launch();
  const ctx = await br.newContext({ viewport: { width: 1400, height: 900 }, acceptDownloads: true }); const page = await ctx.newPage(); const errs = [];
  page.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
  page.on('console', (m) => { if (m.type() === 'error' && !/favicon|Failed to load resource|bad HTTP response code|youtube/i.test(m.text())) errs.push('console: ' + m.text()); });
  await page.goto(base + '/h.html?t=tokA');
  await page.evaluate(([sheets, songs]) => { window.__pv = OPEN({ sheets: sheets, songs: songs }); }, [MULTI, SONGS]);
  const pg = () => page.evaluate(() => document.querySelector('.pv-pg').textContent);
  const songinfo = () => page.evaluate(() => document.querySelector('.pv-songinfo').textContent);
  const sel = () => page.evaluate(() => { const s = document.querySelector('.pv-songsel'); return { v: s.value, shown: getComputedStyle(s).display !== 'none', txt: s.options[s.selectedIndex].textContent }; });
  const next = async () => { await page.click('[data-a="next"]'); await sleep(350); };
  const prev = async () => { await page.click('[data-a="prev"]'); await sleep(350); };

  console.log('1. 쪽별 곡 연결');
  check('4쪽 PDF 열림', await L.waitTrue(page, () => document.querySelector('.pv-pg') && document.querySelector('.pv-pg').textContent === '1 / 4', null, 8000));
  await sleep(1200);                                                          // 제목 검색이 끝날 때까지
  check('1쪽 = Amazing Grace 자동 연결', /Amazing Grace/.test(await songinfo()) && /120 BPM/.test(await songinfo()), await songinfo());
  check('쪽 곡 드롭다운이 보임', (await sel()).shown);
  await next();
  check('2쪽(제목 없음) = 앞 곡이 이어짐', /Amazing Grace/.test(await songinfo()), await songinfo());
  await next();
  check('3쪽 = Second Song 으로 바뀜 (BPM 90)', /Second Song/.test(await songinfo()) && /90 BPM/.test(await songinfo()), await songinfo());
  check('  드롭다운이 자동 · Second Song', /자동/.test((await sel()).txt) && /Second Song/.test((await sel()).txt), await sel());
  await page.click('.pv-tabbtn[data-tab="metro"]'); await sleep(400);
  check('  메트로놈 BPM 도 90 으로', await page.evaluate(() => document.querySelector('[data-role="bpm"]').value) === '90');
  await page.click('.pv-tabbtn[data-tab="form"]'); await sleep(300);
  check('  송폼 패널의 곡도 Second Song', await page.evaluate(() => { const sl = document.querySelector('.pv-pane[data-pane="form"] select'); return !!sl && sl.value === '1'; }), await page.evaluate(() => (document.querySelector('.pv-pane[data-pane="form"] select') || {}).value));
  await prev(); await prev();
  check('1쪽으로 돌아오면 다시 120 BPM', /120 BPM/.test(await songinfo()) && await page.evaluate(() => document.querySelector('[data-role="bpm"]').value) === '120');
  console.log('  · 수동으로 바꾸기');
  await next(); await next();                                                     // 3쪽
  await page.selectOption('.pv-songsel', '0'); await sleep(300);
  check('3쪽을 Amazing Grace 로 직접 지정', /Amazing Grace/.test(await songinfo()) && (await sel()).v === '0', await songinfo());
  await next();
  check('4쪽도 이어서 Amazing Grace', /Amazing Grace/.test(await songinfo()), await songinfo());
  check('기기에 기억됨', await page.evaluate(() => Object.keys(localStorage).some((k) => /yn\.pv\.map\./.test(k))));
  await prev(); await page.selectOption('.pv-songsel', 'auto'); await sleep(300);
  check('자동으로 되돌리면 다시 Second Song', /Second Song/.test(await songinfo()), await songinfo());

  console.log('3. 유튜브 IFrame API — 속도 · A-B 반복');
  await page.evaluate(() => { window.YT = { Player: function (box, cfg) { const p = this; window.__ytp = p; p.cfg = cfg; p.t = 0; p.rate = 1; p.calls = [];
    p.getCurrentTime = () => p.t; p.setPlaybackRate = (r) => { p.rate = r; p.calls.push(['rate', r]); }; p.getAvailablePlaybackRates = () => [0.25, 0.5, 0.75, 1, 1.25, 1.5, 2];
    p.seekTo = (t) => { p.t = t; p.calls.push(['seek', t]); }; p.playVideo = () => p.calls.push(['play']); p.destroy = () => { p.destroyed = true; }; setTimeout(() => cfg.events.onReady({ target: p }), 30); } }; });
  check('Second Song 에 YouTube 버튼', await page.evaluate(() => getComputedStyle(document.querySelector('.pv-ytbtn')).display !== 'none'));
  await page.click('.pv-ytbtn'); await sleep(300);
  check('공식 API 플레이어가 만들어짐 (videoId · nocookie 호스트)', await page.evaluate(() => window.__ytp && window.__ytp.cfg.videoId === 'dQw4w9WgXcQ' && /nocookie/.test(window.__ytp.cfg.host)));
  check('속도 버튼 4개 (0.5 · 0.75 · 1 · 1.25)', await page.evaluate(() => [...document.querySelectorAll('.yt-rates [data-rate]')].map((b) => b.textContent).join() === '0.5x,0.75x,1x,1.25x'));
  check('1x 가 선택된 상태', await page.evaluate(() => document.querySelector('.yt-rates [data-rate="1"]').classList.contains('on')));
  await page.click('.yt-rates [data-rate="0.75"]'); await sleep(100);
  check('0.75x 를 누르면 플레이어 속도가 바뀜', await page.evaluate(() => window.__ytp.rate === 0.75 && document.querySelector('.yt-rates [data-rate="0.75"]').classList.contains('on')));
  await page.evaluate(() => { window.__ytp.t = 12.3; }); await page.click('[data-a="a"]');
  check('A 지정', await page.evaluate(() => /12\.3/.test(document.querySelector('.yt-abinfo').textContent)), await page.evaluate(() => document.querySelector('.yt-abinfo').textContent));
  await page.evaluate(() => { window.__ytp.t = 12.5; }); await page.click('[data-a="b"]');
  check('A 가까이 B 를 찍으면 거절', await page.evaluate(() => /0\.5초/.test(document.querySelector('.yt-msg').textContent)));
  await page.evaluate(() => { window.__ytp.t = 20; }); await page.click('[data-a="b"]'); await sleep(100);
  check('B 지정 → 반복 중 표시', await page.evaluate(() => /반복 중/.test(document.querySelector('.yt-abinfo').textContent) && document.querySelector('.yt-ctl').classList.contains('looping')));
  await page.evaluate(() => { window.__ytp.calls.length = 0; window.__ytp.t = 20.05; }); await sleep(350);
  check('B 에 닿으면 A(12.3초)로 되돌아감', await page.evaluate(() => window.__ytp.calls.some((c) => c[0] === 'seek' && Math.abs(c[1] - 12.3) < 0.01)), await page.evaluate(() => JSON.stringify(window.__ytp.calls)));
  await page.evaluate(() => { window.__ytp.calls.length = 0; window.__ytp.t = 15; }); await sleep(350);
  check('구간 안에서는 건드리지 않음', await page.evaluate(() => !window.__ytp.calls.some((c) => c[0] === 'seek')));
  await page.click('[data-a="clear"]'); await page.evaluate(() => { window.__ytp.calls.length = 0; window.__ytp.t = 25; }); await sleep(350);
  check('해제하면 반복 안 함', await page.evaluate(() => !window.__ytp.calls.some((c) => c[0] === 'seek') && !document.querySelector('.yt-ctl').classList.contains('looping')));
  await page.click('.pv-yth button'); await sleep(100);
  check('닫으면 플레이어가 정리됨', await page.evaluate(() => window.__ytp.destroyed === true && !document.querySelector('.pv-yt')));
  // API 를 못 불러올 때 (오프라인) → 일반 임베드로 대신
  await page.evaluate(() => { delete window.YT; }); await page.evaluate(() => { document.querySelector('.pv-ytbtn').click(); });
  check('API 를 못 불러오면 일반 임베드 + 안내', await L.waitTrue(page, () => document.querySelector('.pv-yt iframe') && /기본 플레이어/.test(document.querySelector('.yt-msg').textContent), null, 12000));
  await page.click('.pv-yth button');

  console.log('4. 전역 단축키');
  const bpmNow = () => page.evaluate(() => document.querySelector('[data-role="bpm"]').value);
  const running = () => page.evaluate(() => /멈춤/.test(document.querySelector('[data-role="toggle"]').textContent));
  await page.evaluate(() => document.activeElement && document.activeElement.blur()); await page.mouse.click(5, 5).catch(() => {});
  await page.evaluate(() => document.activeElement && document.activeElement.blur());
  const p0 = await pg(); await page.keyboard.press('ArrowRight'); await sleep(350);
  const p1 = await pg(); check('→ 다음 쪽', p0 !== p1, p0 + ' → ' + p1);
  await page.keyboard.press('ArrowLeft'); await sleep(350);
  check('← 이전 쪽', (await pg()) === p0, await pg());
  const b0 = +(await bpmNow());
  await page.keyboard.press('ArrowUp'); await sleep(120);
  check('↑ BPM +1', +(await bpmNow()) === b0 + 1, b0 + ' → ' + (await bpmNow()));
  await page.keyboard.press('ArrowDown'); await page.keyboard.press('ArrowDown'); await sleep(120);
  check('↓ BPM −1 (두 번)', +(await bpmNow()) === b0 - 1, await bpmNow());
  await page.keyboard.press('Shift+ArrowUp'); await sleep(120);
  check('Shift+↑ BPM +5', +(await bpmNow()) === b0 + 4, await bpmNow());
  check('Space 전에는 멈춰 있음', !(await running()));
  await page.keyboard.press('Space'); await sleep(250);
  check('Space → 메트로놈 시작', await running());
  await page.keyboard.press('Space'); await sleep(250);
  check('Space 다시 → 멈춤', !(await running()));
  // 버튼에 초점이 남아 있어도 Space 가 그 버튼을 또 누르지 않음
  await page.focus('[data-a="b+"]'); const b1 = +(await bpmNow()); await page.keyboard.press('Space'); await sleep(250);
  check('버튼에 초점이 있어도 Space 는 메트로놈만 (BPM 그대로)', +(await bpmNow()) === b1 && (await running()), await bpmNow());
  await page.keyboard.press('Space'); await sleep(200);
  // 글자 입력 중에는 모두 꺼짐
  await page.evaluate(() => { const i = document.createElement('input'); i.type = 'text'; i.id = 'tmpIn'; document.body.appendChild(i); i.focus(); });
  const p2 = await pg(), b2 = await bpmNow();
  await page.keyboard.press('ArrowRight'); await page.keyboard.press('ArrowUp'); await page.keyboard.press('Space'); await page.keyboard.type('a b'); await sleep(300);
  check('글자 입력 중: 쪽 · BPM · 메트로놈 그대로', (await pg()) === p2 && (await bpmNow()) === b2 && !(await running()));
  check('  입력한 글자는 그대로 들어감 (스페이스 포함)', await page.evaluate(() => document.getElementById('tmpIn').value) === ' a b');
  await page.evaluate(() => { document.getElementById('tmpIn').remove(); });
  await page.evaluate(() => { const t = document.createElement('textarea'); t.id = 'tmpTa'; document.body.appendChild(t); t.focus(); });
  await page.keyboard.press('ArrowDown'); await sleep(100);
  check('textarea 에서도 꺼짐', (await bpmNow()) === b2);
  await page.evaluate(() => document.getElementById('tmpTa').remove());
  await page.selectOption('.pv-songsel', 'auto'); await sleep(200);
  check('목록을 고른 뒤 초점이 풀려 단축키가 바로 됨', await page.evaluate(() => document.activeElement.tagName !== 'SELECT'));

  console.log('7. 필기 개선');
  const P7 = () => page.evaluate(() => window.__pv.P.anno().state());
  const items = (ly) => page.evaluate((l) => window.__pv.P.anno().items(l), ly || 'team');
  await page.evaluate(() => { localStorage.removeItem('yn.pv.layer'); });
  check('"나만 보기" 체크박스가 하나 있고 기본은 체크 안 됨(팀 공유)', await page.evaluate(() => { const c = document.querySelectorAll('.pv-tools input[data-a="mineonly"]'); return c.length === 1 && !c[0].checked && !document.querySelector('.pv-tools [data-a="layer"]') && window.__pv.P.getLayer() === 'team'; }));
  check('예전 팀 공유/나만 보기 토글 버튼은 없음', await page.evaluate(() => !/팀 공유/.test(document.querySelector('.pv-tools').textContent)));
  check('"이 쪽" 대신 "현재 페이지"', await page.evaluate(() => /현재 페이지/.test(document.querySelector('.pv-tools').textContent) && !/이 쪽/.test(document.querySelector('.pv-tools').textContent)));
  await page.click('.pv-tool[data-tool="pen"]'); await sleep(150);
  check('펜 색 6개: 빨강 · 파랑 · 초록 · 보라 · 검정 · 흰색', await page.evaluate(() => [...document.querySelectorAll('.pv-tools .pv-col')].map((b) => b.title.split(' ')[0]).join() === '빨강,파랑,초록,보라,검정,흰색'));
  check('펜에는 글꼴 칸이 없음', await page.evaluate(() => !document.querySelector('.pv-tools .pv-fontrow')));
  await page.click('.pv-tool[data-tool="text"]'); await sleep(150);
  check('글자 도구: 글꼴 5가지(고딕 · 명조 · 손글씨 · 나눔 펜 · 고운돋움) + 크기 숫자 조절기(▲▼) — 긴 슬라이더는 없음', await page.evaluate(() => [...document.querySelectorAll('.pv-tools [data-font] option')].map((o) => o.value).join() === 'sans,serif,hand,pen,dodum' && !!document.querySelector('.pv-tools input[type=number][data-fsz]') && document.querySelectorAll('.pv-tools .pv-nb').length === 2 && !document.querySelector('.pv-tools input[type=range][data-fsz]')));
  await page.click('.pv-tools .pv-col[title="파랑"]'); await sleep(100);
  await L.clickAt(page, .5, .5); await page.waitForSelector('.an-input'); await sleep(150);
  const inpStyle = () => page.evaluate(() => { const i = document.querySelector('.an-input'), cs = getComputedStyle(i); return { color: cs.color, fill: cs.webkitTextFillColor, ff: cs.fontFamily, fs: parseFloat(cs.fontSize), bg: cs.backgroundColor, focus: document.activeElement === i }; });
  let st = await inpStyle();
  check('입력 중 미리보기 글자색 = 고른 색(파랑)', st.color === 'rgb(37, 99, 235)' && st.fill === 'rgb(37, 99, 235)', st);
  await page.keyboard.type('Hello');
  await page.click('.pv-tools .pv-col[title="초록"]'); await sleep(200);
  st = await inpStyle();
  check('치는 도중 색을 바꿔도 입력칸이 남아 있고 바로 초록으로', st.color === 'rgb(22, 163, 74)' && !!(await page.$('.an-input')), st);
  await page.selectOption('.pv-tools [data-font]', 'serif'); await sleep(200);
  st = await inpStyle();
  check('글꼴을 명조로 → 입력칸 글꼴도 명조', /Times New Roman|serif/.test(st.ff) && !!(await page.$('.an-input')), st.ff);
  const fs0 = st.fs;
  const fszVal = () => page.evaluate(() => document.querySelector('.pv-tools input[data-fsz]').value);
  const v0 = +(await fszVal());
  await page.click('.pv-tools .pv-nb[data-step="1"]'); await sleep(120); await page.click('.pv-tools .pv-nb[data-step="1"]'); await sleep(150);
  check('▲ 두 번 → 크기 숫자가 2 커짐', +(await fszVal()) === v0 + 2, { v0, now: await fszVal() });
  await page.click('.pv-tools .pv-nb[data-step="-1"]'); await sleep(150);
  check('▼ 한 번 → 1 줄어듦', +(await fszVal()) === v0 + 1, await fszVal());
  await page.evaluate(() => { const r = document.querySelector('.pv-tools input[data-fsz]'); r.value = '50'; r.dispatchEvent(new Event('input', { bubbles: true })); r.dispatchEvent(new Event('change', { bubbles: true })); }); await sleep(250);
  st = await inpStyle();
  check('숫자 칸에 50 → 입력칸 글자 크기가 커짐', st.fs > fs0 * 1.5 && !!(await page.$('.an-input')), { fs0, fs: st.fs });
  await page.click('.pv-tools .pv-col[title^="흰색"]'); await sleep(150);
  st = await inpStyle();
  check('흰색을 고르면 입력칸 배경이 어두워져 글자가 보임', st.color === 'rgb(255, 255, 255)' && /rgba?\(40, 40, 48/.test(st.bg), st);
  await page.click('.pv-tools .pv-col[title="빨강"]'); await sleep(150);
  await page.keyboard.press('Enter'); await sleep(250);
  let it = (await items('team')).filter((i) => i.t === 'text' && i.s === 'Hello')[0];
  check('확정된 글자: 빨강 · 명조 · 크기 0.05 (미리보기와 같음)', !!it && it.c === '#e53935' && it.f === 'serif' && Math.abs(it.sz - 0.05) < 0.001, it);
  check('기본 층이라 팀 공유 항목으로 저장됨', !!it && (await items('mine')).filter((i) => i.s === 'Hello').length === 0);
  // 코드
  await page.click('.pv-tool[data-tool="chord"]'); await sleep(150);
  await L.clickAt(page, .3, .3); await page.waitForSelector('.an-input'); await page.keyboard.type('G/B'); await page.keyboard.press('Enter'); await sleep(250);
  it = (await items('team')).filter((i) => i.s === 'G/B')[0];
  check('코드에도 글꼴 · 색 적용 (명조 · 빨강 · chord)', !!it && it.chord === 1 && it.f === 'serif' && it.c === '#e53935', it);
  // 기호: 음표 도장
  await page.click('.pv-tool[data-tool="sym"]'); await sleep(200);
  check('기호 도구에도 글꼴 · 크기', await page.evaluate(() => !!document.querySelector('.pv-tools [data-font]') && !!document.querySelector('.pv-tools input[data-fsz]')));
  check('음표 도장 ♩ ♪ ♯ ♭ 이 기호판에 있음', await page.evaluate(() => ['g:quarter', 'g:eighth', 'g:sharp', 'g:flat'].every((k) => !!document.querySelector('.pv-sym[data-k="' + k + '"]'))));
  await page.click('.pv-sym[data-k="g:quarter"]'); await L.clickAt(page, .75, .8); await sleep(250);
  it = (await items('team')).filter((i) => i.t === 'sym' && i.k === 'g:quarter')[0];
  check('♩ 도장이 찍힘 (글꼴 명조 · 빨강)', !!it && it.f === 'serif' && it.c === '#e53935', it);
  await page.click('.pv-sym[data-k="g:flat"]'); await L.clickAt(page, .6, .9); await sleep(250);
  check('♭ 도장도 찍힘', (await items('team')).some((i) => i.k === 'g:flat'));
  // 나만 보기 체크 → 내 층
  await page.click('.pv-tool[data-tool="pen"]'); await page.check('.pv-mineonly input'); await sleep(150);
  check('"나만 보기" 체크 → 내 층으로 바뀜 + 기억됨', await page.evaluate(() => window.__pv.P.getLayer() === 'mine' && localStorage.getItem('yn.pv.layer') === 'mine'));
  await L.drag(page, [[.3, .6], [.5, .62], [.7, .6]]); await sleep(250);
  check('체크한 상태로 쓴 필기는 내 층에만', (await items('mine')).some((i) => i.t === 'pen') && !(await items('team')).some((i) => i.t === 'pen'));
  await page.uncheck('.pv-mineonly input'); await sleep(150);
  check('체크 해제 → 다시 팀 공유', await page.evaluate(() => window.__pv.P.getLayer() === 'team'));
  await page.evaluate(() => { localStorage.removeItem('yn.pv.layer'); });
  await page.click('.pv-tool[data-tool="pen"]');       // 도구 끄기
  await page.click('.pv-tool[data-tool="none"]').catch(() => {});

  console.log('5·6. 아이폰 · 아이패드 반응형 + 자동 여백 맞춤');
  const ph = await br.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 }); const pp = await ph.newPage();
  pp.on('pageerror', (e) => errs.push('phone pageerror: ' + e.message));
  await pp.goto(base + '/h.html?t=tokA'); await pp.click('#go');
  check('폰: 악보가 열림', await L.waitTrue(pp, () => document.querySelector('.pv-pg') && /1 \//.test(document.querySelector('.pv-pg').textContent), null, 8000)); await sleep(1500);
  check('폰: 좁은 화면 배치(pv-compact)', await pp.evaluate(() => document.querySelector('.pv').classList.contains('pv-compact')));
  check('폰: 위쪽 바가 화면 밖으로 넘치지 않음', await pp.evaluate(() => { const t = document.querySelector('.pv-top'); return t.scrollWidth <= t.clientWidth + 1 && document.documentElement.scrollWidth <= innerWidth + 1; }));
  check('폰: 닫기 · 이전 · 다음 · 메뉴 버튼이 모두 화면 안', await pp.evaluate(() => ['[data-a="close"]', '[data-a="prev"]', '[data-a="next"]', '.pv-menubtn'].every((q) => { const r = document.querySelector(q).getBoundingClientRect(); return r.width > 30 && r.left >= 0 && r.right <= innerWidth; })));
  check('폰: 필기 도구가 악보를 가리지 않음 (서랍이 닫혀 있음)', await pp.evaluate(() => { const d = document.querySelector('.pv-drawer'); return getComputedStyle(d).visibility === 'hidden' && !document.querySelector('.pv').classList.contains('pv-drawopen'); }));
  check('폰: 악보 칸이 화면 전체 폭', await pp.evaluate(() => Math.abs(document.querySelector('.pv-stage').getBoundingClientRect().width - innerWidth) < 2));
  await pp.click('.pv-menubtn'); await sleep(450);
  check('폰: 메뉴 버튼 → 서랍이 열림 (aria-expanded)', await pp.evaluate(() => document.querySelector('.pv').classList.contains('pv-drawopen') && document.querySelector('.pv-menubtn').getAttribute('aria-expanded') === 'true'));
  check('폰: 서랍에 확대 · 화면 배치 · 필기 도구가 모두 있음', await pp.evaluate(() => { const d = document.querySelector('.pv-drawer'); return !!d.querySelector('[data-a="zin"]') && !!d.querySelector('[data-a="zfit"]') && !!d.querySelector('[data-layout="tablet"]') && d.querySelectorAll('.pv-tool[data-tool]').length >= 6 && d.querySelectorAll('.pv-col').length >= 6; }));
  check('폰: 서랍이 화면 안에 들어옴', await pp.evaluate(() => { const r = document.querySelector('.pv-drawer').getBoundingClientRect(); return r.right <= innerWidth + 1 && r.left >= 0 && r.width > 200; }));
  await pp.screenshot({ path: '/tmp/shot-phone-drawer.png' });
  await pp.click('.pv-drawer .pv-tool[data-tool="pen"]'); await sleep(450);
  check('폰: 펜을 고르면 서랍이 닫혀 악보를 바로 쓸 수 있음', await pp.evaluate(() => !document.querySelector('.pv').classList.contains('pv-drawopen') && window.YNPractice.current().P.anno().state().tool === 'pen'));
  await pp.click('.pv-menubtn'); await sleep(350); await pp.click('.pv-dback', { position: { x: 20, y: 300 } }); await sleep(350);
  check('폰: 바깥(어두운 부분)을 누르면 서랍이 닫힘', await pp.evaluate(() => !document.querySelector('.pv').classList.contains('pv-drawopen')));
  await pp.click('.pv-menubtn'); await sleep(300); await pp.keyboard.press('Escape'); await sleep(300);
  check('폰: Esc 로도 서랍만 닫힘 (연습 화면은 유지)', await pp.evaluate(() => !document.querySelector('.pv').classList.contains('pv-drawopen') && !!document.querySelector('.pv')));
  await pp.click('.pv-menubtn'); await sleep(300); await pp.click('[data-a="drawer-panel"]'); await sleep(500);
  check('폰: 서랍의 "패널 열기" → 패널 시트', await pp.evaluate(() => document.querySelector('.pv').classList.contains('pv-sideopen') && !document.querySelector('.pv').classList.contains('pv-drawopen')));
  await pp.click('.pv-menubtn'); await sleep(300); await pp.click('.pv-drawer [data-a="zin"]');
  check('폰: 서랍이 열리면 패널 시트는 닫힘', await pp.evaluate(() => !document.querySelector('.pv').classList.contains('pv-sideopen')));
  await pp.keyboard.press('Escape'); await sleep(300);
  // 6. 자동 여백 맞춤
  await pp.click('.pv-menubtn'); await sleep(300); await pp.click('.pv-drawer [data-a="zfit"]'); await sleep(200); await pp.click('.pv-drawer [data-a="zfit"]'); await sleep(700); await pp.keyboard.press('Escape'); await sleep(300);
  const geo = () => pp.evaluate(() => { const st = document.querySelector('.pv-stage'), c = document.querySelector('.pv-pdf'); return { cw: parseFloat(c.style.width), ch: parseFloat(c.style.height), sw: st.clientWidth, sl: st.scrollLeft, stp: st.scrollTop, on: document.querySelector('.pv-cropbtn').classList.contains('on') }; });
  const g1 = await geo();
  check('6: 여백 맞춤이 기본으로 켜져 있음', g1.on, g1);
  check('6: 글자가 있는 부분이 화면 폭을 채움 (종이가 화면보다 크게 확대됨)', g1.cw > g1.sw * 1.6, g1);
  check('6: 글자 시작 위치로 스크롤이 맞춰짐 (제목이 화면 위쪽에 보임)', await pp.evaluate(() => { const c = document.querySelector('.pv-pdf'), st = document.querySelector('.pv-stage'); const cr = c.getBoundingClientRect(), sr = st.getBoundingClientRect(); const ctx = c.getContext('2d'); const sc = c.width / cr.width; const y0 = Math.max(0, (sr.top - cr.top)) * sc, x0 = Math.max(0, sr.left - cr.left) * sc, w = Math.min(cr.width, sr.width) * sc, h = Math.min(120, cr.height) * sc; const d = ctx.getImageData(x0, y0, w, h).data; let n = 0; for (let i = 0; i < d.length; i += 4) if (d[i] < 100) n++; return n > 200; }));
  await pp.click('.pv-menubtn'); await sleep(300); await pp.click('.pv-drawer [data-a="crop"]'); await sleep(700);
  const g2 = await geo();
  check('6: 끄면 종이 전체가 화면에 맞춰짐', !g2.on && g2.cw <= g2.sw + 2 && g2.cw < g1.cw * 0.6, g2);
  await pp.click('.pv-drawer [data-a="crop"]'); await sleep(700);
  check('6: 다시 켜면 확대됨', (await geo()).cw > g2.cw * 1.5);
  // 폰을 눕히면 (가로) 가로 폭 맞춤
  await pp.keyboard.press('Escape'); await pp.setViewportSize({ width: 844, height: 390 }); await sleep(900);
  check('폰 가로: 좁은 화면 배치 유지 + 위쪽 바 넘치지 않음', await pp.evaluate(() => document.querySelector('.pv').classList.contains('pv-compact') && document.querySelector('.pv-top').scrollWidth <= document.querySelector('.pv-top').clientWidth + 1));
  await pp.setViewportSize({ width: 1400, height: 900 }); await sleep(900);
  check('큰 화면으로 돌아오면 서랍 없이 원래 배치 (도구가 화면 위에)', await pp.evaluate(() => !document.querySelector('.pv').classList.contains('pv-compact') && !!document.querySelector('.pv-main > .pv-tools, .pv-main .pv-tools') && !document.querySelector('.pv-drawer .pv-tools') && !!document.querySelector('.pv-top .pv-zoom')));
  await ph.close();

  check('페이지 오류 없음', errs.length === 0, errs);
  await br.close(); S.stop && S.stop();
  process.exit(L.summary() ? 0 : 1);
})().catch((e) => { console.error(e); process.exit(1); });
