process.env.PORT = '4188';
const L = require('./e2e-lib'); const { check, sleep } = L;
require('./e2e-full-server.js');
const { mkpdf, SAMPLE } = require('./mkpdf');
const io = require('socket.io-client');
const BASE = 'http://127.0.0.1:4188', KEY = 'ADM', DATE = '2026-10-04';
const run = (fn) => global.__runtime.run((api) => fn(api)).result;
(async () => {
  await sleep(1200);
  const dataUrl = 'data:application/pdf;base64,' + mkpdf(SAMPLE).toString('base64');
  run((api) => api.saveWorshipSongs(KEY, '2026-09-27', '콘티', [{ title: 'Amazing Grace', team: '테스트', key: 'G', bpm: '120', form: 'V1-C', link: '', note: '', solo: [] }]));
  run((api) => api.saveWorshipSongs(KEY, DATE, '콘티', [{ title: 'Amazing Grace', team: '테스트', key: 'G', bpm: '120', form: 'V1-C-V2-C-B-C', link: '', note: '', solo: [] }, { title: 'Second Song', team: '', key: 'Bb', bpm: '90', form: 'Intro-V-C', link: '', note: '', solo: [] }]));
  const w1 = run((api) => api.uploadWorshipSheet(KEY, DATE, 'Amazing Grace.pdf', dataUrl, '콘티'));
  run((api) => api.uploadWorshipSheet(KEY, DATE, 'Second Song.pdf', dataUrl, '콘티'));
  const fileId = w1.sheets[0].id;
  console.log('· 진짜 서버: 인증 · 악보 스트림');
  const c1 = io(BASE, { transports: ['websocket'] });
  const bad = await new Promise((r) => c1.emit('join', { token: 'WRONG', room: DATE }, r));
  check('틀린 열쇠는 실시간 입장 거부', bad && bad.ok === false && bad.code === 'auth', bad);
  const good = await new Promise((r) => c1.emit('join', { token: KEY, room: DATE }, r));
  check('관리자 열쇠는 입장 · 리더 가능', good && good.ok === true && good.you.canLead === true, good);
  c1.close();
  const st = await fetch(BASE + '/sheet/' + fileId); const buf = Buffer.from(await st.arrayBuffer());
  check('/sheet/<악보ID> 가 PDF 를 돌려줌', st.status === 200 && buf.slice(0, 4).toString() === '%PDF', st.status);
  const st2 = await fetch(BASE + '/sheet/NOTINSHEETXYZ123'); check('목록에 없는 파일은 404', st2.status === 404, st2.status);

  const br = await L.launch(); const ctx = await br.newContext({ viewport: { width: 1280, height: 800 }, acceptDownloads: true }); const page = await ctx.newPage(); const errs = [];
  page.on('pageerror', (e) => errs.push('pageerror: ' + e.message)); page.on('console', (m) => { if (m.type() === 'error' && !/favicon|Failed to load resource|bad HTTP response code/.test(m.text())) errs.push('console: ' + m.text()); });
  await page.goto(BASE + '/?page=worship&key=' + KEY);
  console.log('· 실제 Worship 화면');
  check('허브가 열림', await L.waitTrue(page, () => window.W && window.D, null, 10000));
  await page.evaluate((d) => { if (window.W.date !== d) throw new Error('다른 주 ' + window.W.date); }, DATE).catch(() => {});
  check('악보 목록에 "연습" 버튼', await L.waitTrue(page, () => document.querySelectorAll('.pvgo.mini').length === 2, null, 6000), await page.evaluate(() => document.querySelectorAll('.pvgo').length));
  check('연습 모드 열기 버튼', await page.evaluate(() => !!document.querySelector('button.pvgo:not(.mini)')));
  await page.screenshot({ path: '/tmp/shot-hub.png' });
  await page.click('.pvgo.mini');
  check('연습 화면 열림 · PDF 그려짐', await L.waitTrue(page, () => document.querySelector('.pv') && document.querySelector('.pv-pg') && document.querySelector('.pv-pg').textContent === '1 / 3', null, 10000));
  await sleep(700);
  check('PDF 글자가 보임', (await L.pdfInk(page)) > 500);
  check('악보 이름으로 곡 자동 인식(Key · BPM)', await page.evaluate(() => /Amazing Grace · Key G · 120 BPM/.test(document.querySelector('.pv-songinfo').textContent)), await page.evaluate(() => document.querySelector('.pv-songinfo').textContent));
  check('진짜 서버와 실시간 연결', await L.waitTrue(page, () => /실시간/.test(document.querySelector('.pv-conn').textContent), null, 6000));
  await page.screenshot({ path: '/tmp/shot-computer.png' });
  console.log('· 필기 → 진짜 시트 저장');
  await page.click('.pv-tabbtn[data-tab="together"]'); await page.click('button[data-a="claim"]');
  check('관리자가 리더가 됨', await L.waitTrue(page, () => /내가 리더/.test(document.querySelector('.pv-lead').textContent)));
  await L.ensureTool(page, 'pen'); await page.click('[data-a="layer"]');
  await L.drag(page, [[.2, .3], [.5, .34], [.8, .3]]);
  await page.click('.pv-tabbtn[data-tab="anno"]'); await page.click('button[data-a="save"]');
  let teamRows = [];
  for (let i = 0; i < 30; i++) { teamRows = run((api) => api.찬양주석읽기_(fileId, 'song', '*')); if (teamRows.length) break; await sleep(300); }
  check('팀 필기가 진짜 "찬양주석" 시트에 저장됨', teamRows.length === 1 && teamRows[0].t === 'pen', teamRows);
  await page.evaluate(() => YNPractice.current().P.setLayer('mine')); await L.ensureTool(page, 'pen');
  await L.drag(page, [[.2, .4], [.5, .44], [.8, .4]]);
  let mineRows = [];
  for (let i = 0; i < 30; i++) { mineRows = run((api) => api.찬양주석읽기_(fileId, 'song', '커미티')); if (mineRows.length) break; await sleep(300); }
  check('내 필기(나만 보기)도 시트에 저장됨', mineRows.length === 1, mineRows);
  check('두 층이 섞이지 않음', teamRows[0].id !== (mineRows[0] || {}).id);
  await page.evaluate(() => YNPractice.current().close());
  check('닫으면 화면이 사라짐', await page.evaluate(() => !document.querySelector('.pv') && !document.body.classList.contains('pv-lock')));
  await page.click('.pvgo.mini');
  check('다시 열면 두 층 모두 복원', await L.waitTrue(page, () => YNPractice.current() && YNPractice.current().P.anno().items('team').length === 1 && YNPractice.current().P.anno().items('mine').length === 1, null, 8000), [await L.teamCount(page), await L.mineCount(page)]);

  console.log('· 송폼 만들기');
  await page.evaluate(() => YNPractice.current().close());
  await page.evaluate(() => { songEdit = '콘티:2'; render(); });
  check('송폼 만들기 도구가 곡 수정 안에 나타남', await L.waitTrue(page, () => document.querySelectorAll('#sFormB .fb-btn').length > 10, null, 4000));
  await page.click('#sFormB .fb-t[data-act="clear"]');
  for (const k of ['Intro', 'V1', 'PC', 'C', 'V2', 'C2', 'B1', 'Out']) await page.click('#sFormB .fb-btn[data-add="' + k + '"]');
  const fv = await page.evaluate(() => document.getElementById('sForm').value);
  check('눌러서 만든 순서가 입력칸에 들어감', fv === 'Intro-V1-PC-C-V2-C2-B1-Out', fv);
  await page.evaluate(() => saveSong('콘티', 2));
  check('저장하면 서버 곡 정보에 반영', await L.waitTrue(page, () => W.songs[1] && W.songs[1].form === 'Intro-V1-PC-C-V2-C2-B1-Out', null, 6000), await page.evaluate(() => W.songs.map((s) => s.form)));
  await page.evaluate(() => { songEdit = '콘티:2'; render(); });
  check('다시 열면 송폼 도구가 저장된 값으로 시작', await L.waitTrue(page, () => document.querySelectorAll('#sFormB .fb-chip').length === 8, null, 3000));
  await page.screenshot({ path: '/tmp/shot-form.png' });
  await page.evaluate(() => { songEdit = null; render(); });

  console.log('· 통계 팝업 (다크 글래스)');
  await page.evaluate(() => { TAB = 'stats'; renderTabs && renderTabs(); loadStats(); });
  check('통계 화면', await L.waitTrue(page, () => window.SS && SS.data && document.querySelector('.srow'), null, 8000));
  await page.evaluate(() => statOpen(0));
  check('새 팝업(yg)이 뜸', await L.waitTrue(page, () => document.querySelector('.yg-sh') && document.querySelector('.yg-sh').textContent.length > 20, null, 3000));
  check('예전 밝은 시트(yc)는 안 뜸', await page.evaluate(() => !document.querySelector('.yc-ov')));
  const bg = await page.evaluate(() => getComputedStyle(document.querySelector('.yg-sh')).backgroundImage + '|' + getComputedStyle(document.querySelector('.yg-sh')).backdropFilter);
  check('어두운 유리 배경 + 블러', /gradient/.test(bg) && /blur/.test(bg), bg);
  await sleep(400); await page.screenshot({ path: '/tmp/shot-stats.png' });
  const det = await page.evaluate(() => ({ tiles: document.querySelectorAll('.yg-tiles').length, tl: document.querySelectorAll('.yg-tl li').length, back: document.querySelector('.yg-back').hidden }));
  check('곡 보기: 바로 자세히(타일 + 두 번 부른 기록 2줄)', det.tiles >= 1 && det.tl === 2 && det.back, det);
  await sleep(300); await page.screenshot({ path: '/tmp/shot-song.png' });
  await page.keyboard.press('Escape'); await sleep(300);
  await page.evaluate(() => { SS.view = 'team'; renderTabs && renderTabs(); loadStats && loadStats(); });
  await L.waitTrue(page, () => document.querySelector('.srow'), null, 5000);
  const hasTeam = await page.evaluate(() => { const r = SS.rows.findIndex((x) => x.name === '테스트'); if (r >= 0) statOpen(r); return r; });
  if (hasTeam >= 0) {
    check('팀 → 곡 목록 팝업', await L.waitTrue(page, () => document.querySelectorAll('.yg-row').length >= 1, null, 3000), await page.evaluate(() => document.querySelector('#yg-title') && document.querySelector('#yg-title').textContent));
    await page.click('.yg-row');
    check('곡을 누르면 같은 팝업에서 자세히 + 뒤로 버튼', await L.waitTrue(page, () => document.querySelector('.yg-tiles') && !document.querySelector('.yg-back').hidden, null, 3000));
    await page.click('.yg-back'); check('뒤로 → 목록', await L.waitTrue(page, () => document.querySelector('.yg-rows') && document.querySelector('.yg-back').hidden));
  } else console.log('  (팀 "테스트" 행 없음 — 목록 단계 생략)', await page.evaluate(() => SS.rows.map((x) => x.name)));
  await page.keyboard.press('Escape');
  check('Esc 로 닫힘', await L.waitTrue(page, () => !document.querySelector('.yg-ov'), null, 2000));
  check('닫은 뒤 스크롤 잠금 해제', await page.evaluate(() => document.body.style.overflow !== 'hidden'));
  check('브라우저 오류 없음', errs.length === 0, errs.slice(0, 5));
  await br.close();
  process.exit(L.summary() ? 0 : 1);
})().catch((e) => { console.error('시험 중단:', e); process.exit(2); });
